<!-- Section About And Counter -->
    <section id="about" class="about" style="background:#fff">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <h1>Terms & Conditions </h1>
					
<p>Welcome to the TFG Capital (“TFG Capital”) website. TFG Capital offers flexible, working capital solutions to small businesses in need of financing to sustain or grow their enterprise, including small business loans, purchase and sale of future receivables, and related services (“Service”). By accessing and using this site, you agree to each of the terms and conditions set forth herein (“Terms of Use”). Additional terms and conditions applicable to the specific areas of this site are posted throughout the site and, together with these Terms of Use, govern your use of these areas, content and/or transactions. TFG Capital reserves the right to update the content of its website, including the Terms of Use, at any time without prior notice.</p>
<p>Your use of the site constitutes your agreement to follow and be bound by the terms and conditions of the site, as well as these Terms of Use, as modified. You are encouraged to review the website and these Terms of Use periodically for updates and modification</p>
<h3>1. COPYRIGHT AND TRADEMARK</h3>
<p>Unless otherwise noted, all materials on this site are protected as the copyright, trade dress, trademarks and/or other intellectual properties owned by TFG Capital and/or its subsidiaries and affiliates or by other parties that have licensed their material to TFG Capital.</p>
<p>TFG Capital’s marks on this site represent some of the marks currently owned or controlled in the United States. The display of these marks and of notices associated with these marks is not intended to be a comprehensive combination of all of TFG Capital’s proprietary ownership rights and TFG Capital may own or control other proprietary rights in one or more countries outside of the United States. You may not reproduce, redistribute or otherwise use any materials without the express written consent of TFG Capital or rights not exclusively granted are reserved.</p>
<h3>2. PRIVACY AND SECURITY</h3>
<p>For an explanation of TFG Capital’s practices and policies related to the collection, use and storage of online visitors’ information, please read our <a href="privacy.php" target="_blank" rel="noopener noreferrer">Privacy Policy</a>. The Privacy Policy may be updated from time to time at our discretion. Changes will be effective upon posting to the Website and are hereby incorporated into this Agreement.</p>
<h3>3. WARRANTY DISCLAIMER &amp; LIMITATION OF LIABILITY</h3>
<p>You agree that your use of the website and services shall be at your sole risk. Except as otherwise expressly stated with respect to our products, all contents of this site are offered on an “as is” basis without any warranty whatsoever, either express or implied. TFG Capital makes no representations, express or implied, including, without limitation, implied warranties of marketability and fitness for a particular purpose.</p>
<p>TFG Capital makes no warranties or representations of any kind that the services provided by this website or any link site will be uninterrupted, error-free or that the site or server that hosts the site are free from virus or other forms of harmful computer code or other harmful components, or that defects will be corrected even if TFG Capital is aware of them.</p>
<p>In no event shall TFG Capital, its officers, members, directors, employees, or agents, be liable to you for any direct, indirect, incidental, special, punitive, consequential damages, or attorneys’ fees arising out of or relating to these terms, access to, use of, or the operation of any site, any of the site content, or user content. Your sole and exclusive remedy and TFG Capital’s sole and exclusive liability to you for any reason shall be for you to discontinue your access to or use of the site. The foregoing limitation of liability shall apply to the fullest extent permitted by law in the applicable jurisdiction.</p>
<p>In the event State law does not allow the exclusion or limitation of liability for consequential or incidental damages, TFG Capital’s liability shall be limited and warranties are excluded to the fullest extent permitted by law, but shall in no event exceed $100.00.</p>
<p>You agree that any cause of action arising out of or related to TFG Capital, any website, or any website content or user content must be commenced within one (1) year after the cause of action accrues. Otherwise, such cause of action is permanently barred.</p>
<h3>4. INDEMNIFICATION</h3>
<p>You agree to indemnify, defend, and hold harmless TFG Capital, its affiliates, and partners, including without limitation, TFG Capital’s service providers and banks—and their respective officers, directors, employees, agents, and representatives—from and against all losses, expenses, damages and costs including reasonable attorneys’ fees, for any claims, causes of actions, procedures or allegations arising out of or relating to any violation of these Terms of Use, your use of the website, website content, or user content (including but not limited to infringement of third parties’ worldwide intellectual property rights or negligent or wrongful conduct) by you or any other person accessing any website on your behalf. TFG Capital reserves the right, at its own expense, to assume the exclusive defense and control of any matter otherwise subject to defense by you.</p>
<h3>5. UNLAWFUL OR PROHIBITED USE</h3>
<p>As a condition of your use of the Services, you will not use the Services for any purpose that is unlawful or prohibited by these Terms of Use. You may not use the Services in any manner that could damage, disable, overburden, or impair the TFG Capital website or interfere with any other parties’ use and enjoyment of the Services. You may not attempt to gain unauthorized access to any Services, computer systems or networks connected to any TFG Capital server or to any of the Services through hacking, password mining or any other means. You may not obtain or attempt to obtain any materials or information through any means not intentionally made available through these Services.</p>
<h3>6. EXTERNAL LINKS</h3>
<p>Links to other websites do not imply an endorsement of the materials disseminated at those websites, nor does the existence of a link to another site imply that the organization or person publishing at that site endorses any of the materials at this site. Links to other websites are provided by TFG Capital as a convenience to its users. TFG Capital is not responsible for the materials contained in any website linked to this site. Please be advised that third-party websites may have different terms of use and privacy policies.</p>
<h3>7. AUTHORITY</h3>
<p>Use of the Services is void where prohibited. By using the Services, you represent and warrant that (a) all application information you submit is truthful and accurate; (b) you will maintain the accuracy of such information; (c) you are 18 years of age or older; (d) your use of the Services does not violate any applicable law or regulation; (e) you are authorized on behalf of the company whose name you have entered to apply for business financing. Your profile may be deleted and your Membership may be terminated without warning if we believe, in our sole discretion, that you are in violation of any Terms of Use.</p>
<p>You understand and agree that TFG Capital and our agents and assignees are authorized to contact third parties to conduct background checks and other investigative reports and make credit report inquiries (including requesting business and personal credit bureau reports from credit reporting agencies and other sources) or for any other lawful purpose, and that TFG Capital has the authority for the foregoing in connection with any update, renewal, or extension of the credit to the company on whose behalf you are applying for credit. Upon your written request, we will advise you if we obtained a credit report. You understand and agree that TFG Capital is making no commitment or guarantee that any product, evaluation, or guidance provided by TFG Capital will result in an approval for funding.</p>
<h3>8. ACCOUNT SECURITY</h3>
<p>Customer Duty – You agree to keep confidential all passwords, user IDs, IP addresses and other account identifiers and are solely responsible for any liability or damages resulting from your failure to maintain that confidentiality. You are solely and fully responsible and liable for all activities that occur under your TFG Capital account, password, user ID or IP address. You agree to:</p>
<p>(a) Immediately notify TFG Capital if you suspect any breach of security such as loss, theft, public use (unrestricted, open, communal or shared use by third parties unrelated and/or not affiliated with the customer either for profit or not-for-profit) or unauthorized disclosure or use of your TFG Capital account, password, user ID or any credit or charge card numbers provided to TFG Capital by calling 718-875-0556;</p>
<p>(b) Ensure your exit from your account as applicable at the end of each session; and</p>
<p>(c) Periodically change your password.</p>
<p>Account Access – You authorize TFG Capital to provide information about and make changes to your TFG Capital account including adding new services on the direction of any person able to provide information we deem sufficient to identify you.</p>
<p>Assumption of Risk – There is a risk that other(s) may attempt to access your services, such as through the internet or connected networks. You acknowledge this risk is inherent to the shared nature of the services and you agree to take full responsibility for taking adequate security precautions and safeguarding your data.</p>
<h3>9. ELECTRONIC COMMUNICATIONS</h3>
<p>By using parts of this website, or sending e-mails to TFG Capital, you agree to receive communications from us electronically, and that all agreements, notices, disclosures and other communications that we, our affiliates, partners or independent contractors provide to you electronically satisfy any legal requirement that such communication be in writing and are effective immediately.</p>
<p>You have the right to withdraw your consent to receive disclosures and submit information electronically. You may withdraw your consent by contacting the Company in writing. If you choose to withdraw your consent, you will not be able to make any requests through our website. If you have a pending request on our website, we will terminate it and remove it from our system. If you have already received funding, all previously agreed to terms and conditions will remain in effect, and we will send disclosures to your verified business address provided during registration.</p>
<p>You may obtain a free copy of your electronic application by contacting the Company in writing at 300 Cadman Plaza West, One Pierrepont Plaza 12th Floor
Brooklyn, New York, 11201 or by telephone at 718-875-0556.</p>
<h3>10. TELEPHONE COMMUNICATIONS</h3>
<p>You hereby expressly consent to receiving calls and messages, including auto-dialed and pre-recorded message calls and SMS messages (including text messages) from TFG Capital, its affiliates, marketing partners, agents and others calling at TFG Capital’s request or on its behalf, at any telephone numbers that you have provided or may provide in the future (including any cellular or mobile telephone numbers). Your cellular or mobile telephone provider will charge you according to the type of plan you carry. You may opt out of receiving calls and marketing from TFG Capital and its affiliates, marketing partners, agents and others as provided in the Privacy Policy or by contacting us directly.</p>
<h3>11. GOVERNING LAW AND FORUM</h3>
<p>Jurisdiction – Any dispute arising from these terms shall be resolved exclusively in the State and Federal Courts of the State of New York. Furthermore, these terms and the interpretation, performance and enforcement of your and TFG Capital’s rights and duties shall be construed in accordance with the laws of the State of New York except for the conflict or choice of law principles thereof.</p>
<h3>12. FEEDBACK AND SUBMISSIONS</h3>
<p>You agree you are and shall remain solely responsible for the content of any submissions you make and you will not submit material that is unlawful, defamatory, abusive or obscene. You agree that you will not submit anything to the site that will violate any right of any third party, including copyright, trademark, privacy or any other personal or proprietary rights.</p>
<h3>13. FORCE MAJEURE</h3>
<p>TFG Capital shall not be liable for any failure or delay in performance due in whole or in part to any cause beyond the reasonable control of such party or its contractors, agents or suppliers, including but not limited to utility or transmission failures, power failure, strikes or other labor disturbances, acts of God, acts of war or terror, floods, sabotage, fire, natural or other disasters.</p>
<h3>14. CONTACTING TFG Capital</h3>
<p>In the event you should have any questions about these terms, please contact us at 718-875-0556. To inquire about linking to our site or about copyright or trademark matters, please contact us at <a href="mailto:care@tfgcapital.net" target="_blank" rel="noopener noreferrer">care@tfgcapital.net</a>.</p>

					
                </div>
            </div>
            
        </div>
    </section> 
    <!-- End Section Of About And Counter -->

